<?php

namespace techeventBundle\Repository;

/**
 * ArchiveRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArchiveRepository extends \Doctrine\ORM\EntityRepository
{
}
