<?php

namespace techeventBundle\Repository;

/**
 * avisRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class avisRepository extends \Doctrine\ORM\EntityRepository
{
}
