<?php

namespace techeventBundle\Repository;

/**
 * chatRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class chatRepository extends \Doctrine\ORM\EntityRepository
{
}
