Copon:
    type: entity
    table: copon
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        codecoupon:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
            column: codeCoupon
    lifecycleCallbacks: {  }
