Reservation:
    type: entity
    table: reservation
    indexes:
        IDX_4DA239A76ED395:
            columns:
                - user_id
        IDX_4DA23971F7E88B:
            columns:
                - event_id
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        datereservation:
            type: datetime
            nullable: false
            options:
                default: CURRENT_TIMESTAMP
            column: dateReservation
        quantite:
            type: integer
            nullable: false
            options:
                unsigned: false
        total:
            type: float
            nullable: false
            precision: 10
            scale: 0
        type:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
        seat:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
        payer:
            type: integer
            nullable: true
            options:
                unsigned: false
        nomreservation:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
            column: nomReservation
    manyToOne:
        event:
            targetEntity: Event
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                event_id:
                    referencedColumnName: id
            orphanRemoval: false
        user:
            targetEntity: FosUser
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                user_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
