<?php

namespace AppelSponsorBundle\Repository;

/**
 * dossierSponsoringRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class dossierSponsoringRepository extends \Doctrine\ORM\EntityRepository
{
}
